#!/bin/bash


wget -P /etc/nginx/conf.d https://raw.githubusercontent.com/rxyxxy/SSPanel-Uim/rnm/SSPanel-Uim.conf

git clone -b 2023.7 https://github.com/rxyxxy/SSPanel-Uim.git
cd SSPanel-Uim
wget https://getcomposer.org/installer -O composer.phar
php composer.phar
php composer.phar install --no-dev

chmod -R 755 *
chown -R www-data:www-data *

cp config/.config.example.php config/.config.php
cp config/appprofile.example.php config/appprofile.php

sed -i "s|['db_database'] = 'sspanel';|['db_database'] = '$DATA_NAME';|g" filename
sed -i "s|['db_username'] = 'root';|['db_username'] = '$DATA_USER';|g" filename
sed -i "s|['db_password'] = 'sspanel';|['db_password'] = '$DATA_PW';|g" filename
sed -i "s|['db_port'] = '3306';|['db_port'] = '$DATA_PORT';|g" filename

service nginx start

php /app/SSPanel-Uim/php xcat Update
while true; do php /app/SSPanel-Uim/xcat Cron 2>&1 && echo "SSPanel 的基本 cron 任务" && sleep 3000; done &
